# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='\u586b\u5199\u6807\u9898', max_length=64, unique=True, verbose_name='\u6807\u9898')),
                ('categroy', models.CharField(choices=[(b'stu_dairy', '\u5b66\u5458\u65e5\u8bb0'), (b'good_news', '\u5c31\u4e1a\u559c\u62a5'), (b'school_news', '\u5b66\u6821\u516c\u544a')], max_length=32, verbose_name='\u6587\u7ae0\u7c7b\u578b')),
                ('link', models.URLField(verbose_name='\u6587\u7ae0\u94fe\u63a5')),
                ('priority', models.IntegerField(help_text='\u6587\u7ae0\u6392\u540d\u6743\u91cd,\u503c\u8d8a\u5c0f,\u6392\u540d\u8d8a\u9760\u524d', verbose_name='\u6743\u91cd')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hide', models.BooleanField(default=False, verbose_name='\u9690\u85cf\u6b64\u6587\u7ae0')),
            ],
        ),
    ]
