# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewGraduates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=64, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('semester', models.CharField(max_length=32, verbose_name='\u5b66\u671f')),
                ('graduate_date', models.DateField(default=django.utils.timezone.now, verbose_name='\u6bd5\u4e1a\u65e5\u671f')),
                ('average_salary', models.IntegerField(default=10000, help_text='\u5199\u6570\u5b57', verbose_name='\u5e73\u5747\u5de5\u8d44')),
                ('stu_num', models.IntegerField(default=65, help_text='\u5199\u6570\u5b57', verbose_name='\u73ed\u7ea7\u4eba\u6570')),
                ('link', models.URLField(verbose_name='\u8be6\u7ec6\u5217\u8868')),
                ('img', models.ImageField(help_text='\u786e\u4fdd\u56fe\u7247\u88c1\u526a\u81f3650x397,\u4e14\u5206\u8fa8\u7387\u4e3a300', upload_to=b'statics/img/home//', verbose_name='\u9875\u9762\u663e\u793a\u56fe\u7247')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='\u586b\u5199\u6807\u9898', max_length=64, unique=True, verbose_name='\u6807\u9898')),
                ('category', models.CharField(choices=[(b'stu_dairy', '\u5b66\u5458\u65e5\u8bb0'), (b'good_news', '\u559c\u62a5'), (b'school_news', '\u516c\u544a'), (b'news_class', '\u6700\u65b0\u5f00\u73ed')], max_length=32, verbose_name='\u6587\u7ae0\u7c7b\u578b')),
                ('link', models.URLField(verbose_name='\u6587\u7ae0\u94fe\u63a5')),
                ('priority', models.IntegerField(default=1000, help_text='\u6587\u7ae0\u6392\u540d\u6743\u91cd,\u503c\u8d8a\u5c0f,\u6392\u540d\u8d8a\u9760\u524d', verbose_name='\u6743\u91cd')),
                ('class_open_date', models.DateField(blank=True, help_text="\u4ec5\u5728\u6587\u7ae0\u7c7b\u578b\u4e3a'\u6700\u65b0\u5f00\u73ed'\u65f6\u624d\u4f7f\u7528\u6b64\u9879,\u9009\u62e9\u5f00\u73ed\u65e5\u671f", null=True, verbose_name='\u5f00\u73ed\u65e5\u671f')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hide', models.BooleanField(default=False, verbose_name='\u9690\u85cf\u6b64\u6587\u7ae0')),
            ],
        ),
        migrations.CreateModel(
            name='PublicClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='\u516c\u5f00\u8bfe\u4e3b\u9898...', max_length=128, unique=True, verbose_name='\u4e3b\u9898')),
                ('start_date', models.DateTimeField(verbose_name='\u5f00\u8bfe\u65f6\u95f4')),
                ('teacher', models.CharField(max_length=32, verbose_name='\u8bb2\u5e08')),
                ('link', models.URLField(verbose_name='\u62a5\u540d\u94fe\u63a5')),
                ('img', models.ImageField(help_text='\u786e\u4fdd\u56fe\u7247\u88c1\u526a\u81f3650x397,\u4e14\u5206\u8fa8\u7387\u4e3a300', upload_to=b'statics/img/home/public_class/', verbose_name='\u9875\u9762\u663e\u793a\u56fe\u7247')),
            ],
        ),
    ]
