# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlinks',
            name='categroy',
            field=models.CharField(choices=[(b'stu_dairy', '\u5b66\u5458\u65e5\u8bb0'), (b'good_news', '\u559c\u62a5'), (b'school_news', '\u516c\u544a'), (b'school_news', '\u6700\u65b0\u5f00\u73ed')], max_length=32, verbose_name='\u6587\u7ae0\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='notificationlinks',
            name='priority',
            field=models.IntegerField(default=1000, help_text='\u6587\u7ae0\u6392\u540d\u6743\u91cd,\u503c\u8d8a\u5c0f,\u6392\u540d\u8d8a\u9760\u524d', verbose_name='\u6743\u91cd'),
        ),
    ]
