# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq', models.IntegerField(unique=True, verbose_name='qq')),
                ('name', models.CharField(max_length=32, verbose_name='\u62db\u751f\u8001\u5e08\u59d3\u540d')),
                ('monday', models.BooleanField(default=True, verbose_name='\u5468\u4e00')),
                ('tuesday', models.BooleanField(default=True, verbose_name='\u5468\u4e8c')),
                ('wednesday', models.BooleanField(default=True, verbose_name='\u5468\u4e09')),
                ('thursday', models.BooleanField(default=True, verbose_name='\u5468\u56db')),
                ('friday', models.BooleanField(default=True, verbose_name='\u5468\u4e94')),
                ('saturday', models.BooleanField(default=True, verbose_name='\u5468\u516d')),
                ('sunday', models.BooleanField(default=True, verbose_name='\u5468\u65e5')),
            ],
        ),
    ]
