# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 13:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_consultants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u5b66\u5458\u540d\u79f0')),
                ('education', models.CharField(choices=[(1, '\u5c0f\u5b66'), (2, '\u521d\u4e2d'), (3, '\u9ad8\u4e2d'), (4, '\u4e2d\u4e13'), (5, '\u5927\u4e13'), (6, '\u672c\u79d1'), (7, '\u7855\u58eb'), (8, '\u535a\u58eb')], max_length=100, verbose_name='\u5b66\u5386')),
                ('course', models.CharField(max_length=100, verbose_name='\u8bfe\u7a0b')),
                ('enterprise', models.CharField(max_length=100, verbose_name='\u5de5\u4f5c\u5355\u4f4d')),
                ('salary', models.IntegerField(default=10000, verbose_name='\u85aa\u6c34')),
                ('time', models.DateTimeField(default=datetime.datetime(2016, 5, 16, 13, 21, 35, 205004, tzinfo=utc))),
            ],
        ),
    ]
