# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_offor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offor',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
