# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160516_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offor',
            name='course',
            field=models.IntegerField(default=6, verbose_name='\u8bfe\u7a0b'),
        ),
    ]
