# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160201_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='\u516c\u5f00\u8bfe\u4e3b\u9898...', max_length=128, unique=True, verbose_name='\u4e3b\u9898')),
                ('start_date', models.DateTimeField(verbose_name='\u5f00\u8bfe\u65f6\u95f4')),
                ('teacher', models.CharField(max_length=32, verbose_name='\u8bb2\u5e08')),
                ('link', models.URLField(verbose_name='\u62a5\u540d\u94fe\u63a5')),
                ('img', models.ImageField(help_text='\u786e\u4fdd\u56fe\u7247\u88c1\u526a\u81f3650x370,\u4e14\u5206\u8fa8\u7387\u4e3a300', upload_to=b'img/home/public_class/', verbose_name='\u9875\u9762\u663e\u793a\u56fe\u7247')),
            ],
        ),
    ]
