# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 10:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_publicclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewGraduates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=64, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('semester', models.CharField(max_length=32, verbose_name='\u5b66\u671f')),
                ('graduate_date', models.DateField(default=datetime.datetime(2016, 2, 4, 10, 9, 41, 431835, tzinfo=utc), verbose_name='\u6bd5\u4e1a\u65e5\u671f')),
                ('average_salary', models.IntegerField(default=10000, help_text='\u5199\u6570\u5b57', verbose_name='\u5e73\u5747\u5de5\u8d44')),
                ('link', models.URLField(verbose_name='\u8be6\u7ec6\u5217\u8868')),
                ('img', models.ImageField(help_text='\u786e\u4fdd\u56fe\u7247\u88c1\u526a\u81f3650x397,\u4e14\u5206\u8fa8\u7387\u4e3a300', upload_to=b'statics/img/home//', verbose_name='\u9875\u9762\u663e\u793a\u56fe\u7247')),
            ],
        ),
        migrations.AlterField(
            model_name='publicclass',
            name='img',
            field=models.ImageField(help_text='\u786e\u4fdd\u56fe\u7247\u88c1\u526a\u81f3650x397,\u4e14\u5206\u8fa8\u7387\u4e3a300', upload_to=b'statics/img/home/public_class/', verbose_name='\u9875\u9762\u663e\u793a\u56fe\u7247'),
        ),
    ]
