# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20160516_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offor',
            name='course',
            field=models.CharField(max_length=100, verbose_name='\u8bfe\u7a0b'),
        ),
        migrations.AlterField(
            model_name='offor',
            name='education',
            field=models.IntegerField(choices=[(1, '\u5c0f\u5b66'), (2, '\u521d\u4e2d'), (3, '\u9ad8\u4e2d'), (4, '\u4e2d\u4e13'), (5, '\u5927\u4e13'), (6, '\u672c\u79d1'), (7, '\u7855\u58eb'), (8, '\u535a\u58eb')], default=6, verbose_name='\u5b66\u5386'),
        ),
    ]
