# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-17 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20160516_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('link', models.URLField(blank=True, verbose_name='\u94fe\u63a5')),
                ('priority', models.IntegerField(default=1000, help_text='\u94fe\u63a5\u6392\u540d\u6743\u91cd,\u503c\u8d8a\u5c0f,\u6392\u540d\u8d8a\u9760\u524d', verbose_name='\u6743\u91cd')),
                ('type', models.IntegerField(choices=[(1, '\u9996\u9875\u8f6e\u64ad\u56fe'), (2, '\u9996\u9875\u57f9\u8bad\u8bfe\u7a0b\u56fe'), (3, '\u9996\u9875\u5e08\u8d44\u4ecb\u7ecd\u56fe'), (4, '\u9996\u9875\u7f51\u7edc\u5b66\u4e60\u4e2d\u5fc3'), (5, '\u9996\u9875\u793e\u533a\u63a8\u8350')], default=1, verbose_name='\u7c7b\u578b')),
                ('img', models.ImageField(upload_to=b'static/img/home', verbose_name='\u56fe\u7247')),
            ],
        ),
        migrations.AlterField(
            model_name='notificationlinks',
            name='category',
            field=models.CharField(choices=[(b'stu_dairy', '\u5b66\u5458\u65e5\u8bb0'), (b'good_news', '\u559c\u62a5'), (b'school_news', '\u516c\u544a'), (b'news_class', '\u6700\u65b0\u5f00\u73ed'), (b'senior_dairy', '\u5e08\u5144\u8bf4'), (b'net_class', '\u7f51\u7edc\u5b66\u4e60\u4e2d\u5fc3')], max_length=32, verbose_name='\u6587\u7ae0\u7c7b\u578b'),
        ),
    ]
