# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20160204_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgraduates',
            name='graduate_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='\u6bd5\u4e1a\u65e5\u671f'),
        ),
    ]
