# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20160204_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgraduates',
            name='stu_num',
            field=models.IntegerField(default=65, help_text='\u5199\u6570\u5b57', verbose_name='\u73ed\u7ea7\u4eba\u6570'),
        ),
    ]
