# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-23 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20160517_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelink',
            name='type',
            field=models.IntegerField(choices=[(1, '\u9996\u9875\u8f6e\u64ad\u56fe'), (2, '\u9996\u9875\u57f9\u8bad\u8bfe\u7a0b\u56fe'), (3, '\u9996\u9875\u5e08\u8d44\u4ecb\u7ecd\u56fe'), (4, '\u9996\u9875\u7f51\u7edc\u5b66\u4e60\u4e2d\u5fc3'), (5, '\u9996\u9875\u793e\u533a\u63a8\u8350'), (6, '\u7f51\u7edc\u8bfe\u7a0b')], default=1, verbose_name='\u7c7b\u578b'),
        ),
    ]
